export function DINotFoundException(message) {
   return new Error(message)
}
